import type { Question } from '@/types/onboarding';

/** Multi-step questionnaire (frontend-only); aligned with virtual-coach flow, Tai Chi–oriented copy. */
export const onboardingQuestions: Question[] = [
  {
    id: 'age',
    title: 'Personalize your Tai Chi practice',
    subtitle: 'Enter your age to get started:',
    type: 'text-input',
    required: true,
    placeholder: 'e.g., 25',
  },
  {
    id: 'gender',
    title: 'Personalize your Tai Chi practice',
    subtitle: 'Select your gender:',
    type: 'image-select',
    required: true,
    options: [
      { id: 'male', label: 'Male', value: 'male', icon: '💪' },
      { id: 'female', label: 'Female', value: 'female', icon: '💃' },
    ],
  },
  {
    id: 'height',
    title: 'What is your height?',
    type: 'text-input',
    required: true,
    placeholder: "e.g., 170 cm or 6'0\"",
  },
  {
    id: 'weight',
    title: 'What is your current weight?',
    type: 'text-input',
    required: true,
    placeholder: 'e.g., 160 lbs',
  },
  {
    id: 'practice-goals',
    title: 'What are your main goals with Tai Chi?',
    type: 'multi-select',
    required: true,
    validation: { minSelections: 1 },
    options: [
      { id: 'balance', label: 'Balance & stability', value: 'balance', icon: '⚖️' },
      { id: 'stress', label: 'Stress relief & mindfulness', value: 'stress', icon: '🧘' },
      { id: 'mobility', label: 'Mobility & flexibility', value: 'mobility', icon: '🤸' },
      { id: 'strength', label: 'Gentle strength', value: 'strength', icon: '💪' },
    ],
  },
  {
    id: 'experience-level',
    title: 'How would you describe your movement experience?',
    type: 'single-select',
    required: true,
    options: [
      { id: 'beginner', label: 'Beginner', value: 'beginner', icon: '🌱' },
      { id: 'intermediate', label: 'Intermediate', value: 'intermediate', icon: '🏃' },
      { id: 'advanced', label: 'Advanced', value: 'advanced', icon: '🔥' },
    ],
  },
  {
    id: 'focus-areas',
    title: 'What would you like to emphasize?',
    type: 'multi-select',
    required: true,
    validation: { minSelections: 1 },
    options: [
      { id: 'lower-body', label: 'Legs & stance work', value: 'lower-body', icon: '🦵' },
      { id: 'upper-body', label: 'Arms & silk-reeling', value: 'upper-body', icon: '💪' },
      { id: 'breath', label: 'Breath coordination', value: 'breath', icon: '🌬️' },
      { id: 'form', label: 'Form memory & flow', value: 'form', icon: '🌀' },
    ],
  },
  {
    id: 'injured-areas',
    title: 'Any areas to be careful with? (optional)',
    type: 'multi-select',
    required: false,
    validation: { minSelections: 0 },
    options: [
      { id: 'back', label: 'Back', value: 'back', icon: '🦴' },
      { id: 'knees', label: 'Knees', value: 'knees', icon: '🦵' },
      { id: 'shoulders', label: 'Shoulders', value: 'shoulders', icon: '🤸' },
      { id: 'neck', label: 'Neck', value: 'neck', icon: '🧑' },
      { id: 'hips', label: 'Hips', value: 'hips', icon: '🧍' },
      { id: 'na', label: 'N/A', value: 'na', icon: '✓' },
    ],
  },
  {
    id: 'practice-location',
    title: 'Where will you usually practice?',
    type: 'single-select',
    required: true,
    options: [
      { id: 'home', label: 'Home', value: 'home', icon: '🏠' },
      { id: 'outdoor', label: 'Outdoors / park', value: 'outdoor', icon: '🌳' },
      { id: 'studio', label: 'Studio / class', value: 'studio', icon: '🏛️' },
    ],
  },
  {
    id: 'space-size',
    title: 'How much open floor space do you have?',
    type: 'multi-select',
    required: false,
    validation: { minSelections: 0 },
    options: [
      { id: 'small', label: 'Small (arms-length)', value: 'small', icon: '📐' },
      { id: 'medium', label: 'Medium (few steps)', value: 'medium', icon: '↔️' },
      { id: 'large', label: 'Large (full form)', value: 'large', icon: '📏' },
    ],
  },
  {
    id: 'practice-frequency',
    title: 'How many days per week can you practice?',
    type: 'single-select',
    required: true,
    options: [
      { id: '2', label: '2 days', value: '2', icon: '📅' },
      { id: '3', label: '3 days', value: '3', icon: '📅' },
      { id: '5', label: '5 days', value: '5', icon: '📅' },
    ],
  },
  {
    id: 'practice-days',
    title: 'Which days work best?',
    type: 'multi-select',
    required: true,
    validation: { minSelections: 1 },
    options: [
      { id: 'sunday', label: 'Sunday', value: 'sunday', icon: '📅' },
      { id: 'monday', label: 'Monday', value: 'monday', icon: '📅' },
      { id: 'tuesday', label: 'Tuesday', value: 'tuesday', icon: '📅' },
      { id: 'wednesday', label: 'Wednesday', value: 'wednesday', icon: '📅' },
      { id: 'thursday', label: 'Thursday', value: 'thursday', icon: '📅' },
      { id: 'friday', label: 'Friday', value: 'friday', icon: '📅' },
      { id: 'saturday', label: 'Saturday', value: 'saturday', icon: '📅' },
    ],
  },
];
